решил первую задачу
js-tasks-ru/jsbasic-20200903_yuriy-yupiter pull request #1
Opened 2020-09-03 00:15 UTC by Yupiter78

2020-09-03 00:23 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-03 15:37 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-03 19:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-04 07:09 UTC, koalex requested changes
Исправь замечания и отправь на ревью заново мне.

2020-09-04 07:09 UTC, koalex commented on 0-module/1-task/index.js
> + sum(1, 1);
Удали строку 11 и 12. В решении не должно быть вызовов этих ф-ций.

2020-09-04 07:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-04 17:19 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-04 17:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Первая задача
- 1+1=2
```

2020-09-04 17:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-05 06:29 UTC, koalex approved these changes
Всё ОК

2020-09-05 06:29 UTC, merged